variable "infra_env" {}
variable "db_name" {}
variable "allocated_storage" {}
variable "engine" {}
variable "engine_version" {}
variable "instance_class" {}
variable "username" {}
variable "vpc_security_group_ids" {}
variable "availability_zone" {}
variable "subnet_ids" {}
variable "identifier" {}